// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Buku struct {
	ID                int64  `json:"id"`
	Judul             string `json:"judul"`
	Penulis           string `json:"penulis"`
	Kuantitas         int32  `json:"kuantitas"`
	TempatPenyimpanan string `json:"tempat_penyimpanan"`
}

type Mahasiswa struct {
	ID      int64  `json:"id"`
	Nama    string `json:"nama"`
	Nim     string `json:"nim"`
	Jurusan string `json:"jurusan"`
}

type Peminjaman struct {
	ID                       int64       `json:"id"`
	MahasiswaID              pgtype.Int8 `json:"mahasiswa_id"`
	BukuID                   pgtype.Int8 `json:"buku_id"`
	TanggalPeminjaman        pgtype.Date `json:"tanggal_peminjaman"`
	TanggalBatasPengembalian pgtype.Date `json:"tanggal_batas_pengembalian"`
	TanggalPengembalian      pgtype.Date `json:"tanggal_pengembalian"`
}
